import svgwrite
from Bio import AlignIO


def CUSTOM_ALIGN(targetfile):
	alignments_to_keep = {}
	with open(targetfile,"r") as alignfile:
		for record in AlignIO.read(alignfile,"clustal"):
			try:
				seq_name = record.id.split("_")[1]
			except:
				seq_name = record.id
			seq = record.seq
			if alignments_to_keep.has_key(seq_name)==False:
				alignments_to_keep[seq_name]=str(seq)
	return alignments_to_keep
# ---------------------------------------------------------------------------------------------------------------------------------------------
def conservation_checker(identifier, seqdict):
	for protein in  seqdict:
		sequence = seqdict[protein]
		if protein == identifier:
			truesequenzler = sequence
	sequencelength = len(truesequenzler) ### including gaps, meaning this is the alignment length
	positionalcounter = 1

	conservational_dictionary = {}
	theforbiddenalignpos = []
	for i in range(0,sequencelength):
		identitycontainer = []
		for ident in seqdict:
			if ident == identifier:
				orires = seqdict[ident][i]
				identitycontainer.append(seqdict[ident][i])
			else:
				identitycontainer.append(seqdict[ident][i])
		identitypercentage = float(identitycontainer.count(orires))/float(len(identitycontainer))	### so far this also includes "-" as the original truesequence residue, be cautious
		oritype = "none"

		if orires != "-":
#			print positionalcounter,"\t", identitycontainer, "\t", orires,"\t",identitypercentage,"\t",typuspercentage ,"\t", aminotypes,"\t",oritype
			if conservational_dictionary.has_key(int(positionalcounter))==False:
				conservational_dictionary[int(positionalcounter)] = [float(identitypercentage), orires]
			positionalcounter+=1
		elif orires == "-":
			if identitypercentage >= 0.90:
				theforbiddenalignpos.append(i+1)	
		else:
			pass
	return conservational_dictionary, theforbiddenalignpos	
# ---------------------------------------------------------------------------------------------------------------------------------------------
def SHOWORDER(seqs, doi, starti, endi, goi):
	# dictionary of interest, residue of interest, windowsize, gene of interest
	showtime = {}
	for k in doi:	### uniprot ID = k
		featurecount = []
		sequenzler = seqs[k]
		residue = 0
		for i, letter in enumerate(sequenzler,start = 1):
			if letter != "-":
				residue += 1
				if i >= starti:
					if i <= endi:
						for v in doi[k]: ### categories, i.e. VARIANT = v
							for vv in doi[k][v]:	### residue number = vv
								if int(vv) == residue:
									if int(vv) not in featurecount:
										featurecount.append(vv)
		if showtime.has_key(k)==False:
			showtime[k]=len(featurecount)
	#print showtime
	ranking = sorted(showtime, key=lambda x: (-showtime[x], x))
	#print ranking
	#for ranked in ranking:
	#	print ranked, "\t", showtime[ranked]
	return ranking
# ---------------------------------------------------------------------------------------------------------------------------------------------
def create_svg(sequences_dict, positions, colordict, startposition, windowsize, poi, forbidden, proteinfeatures):
    #### do this when havng constructed the dictionary with interesting positions
    #### here it is supplied as is, but needs to be further modified
    for item in positions:
        for categ in colordict:
            if positions[item].has_key(categ)==False:
                positions[item][categ]=[]
    dwg = svgwrite.Drawing('sequence.svg', profile='full')
    x = 50
    y = 80
    sequence_of_interest = sequences_dict[poi]
    non_minus_count = 0
    distance_end = len(sequence_of_interest)+100	### to make sure it gets weeded out below, if none of the if statements directly below trigger
    distance_start = 0					### to make sure it gets weeded out below, if none of the if statements directly below trigger
    for i, letter in enumerate(sequence_of_interest,start = 1):
	if letter != "-":
		non_minus_count += 1
		if non_minus_count == startposition:
			startpos = i	### this is the alignment position that corresponds to the residue of interest. alignmpent position includes "-"
		if non_minus_count == startposition+windowsize:
			distance_end = i
		if non_minus_count == startposition-windowsize:
			distance_start = i
    maxcharactercnt = non_minus_count		### should capture the true length of the sequence of interest

    roworder = SHOWORDER(sequences_dict, positions, distance_start, distance_end, poi)
    for uniprot in sequences_dict:
	if uniprot not in roworder:
		roworder.append(uniprot)

    #distance_start = startpos - windowsize
    #distance_end = startpos + windowsize + 1
    ### make sure the windowsize does not conflict with positions close to the start or end of the sequence
    if distance_start <= 0:
	distance_start = 1
    if distance_end > len(sequence_of_interest):
	distance_end = len(sequence_of_interest)


    maximumdistance = distance_end - distance_start
    viewboxcounter = 1
    for uniprot in roworder:
	seq 	= sequences_dict[uniprot]
	namus 	= uniprot
	startingpoint = startposition - windowsize	### this is required for the correct labeling according to the sequence of interest
	if namus == poi:	##### this if/else conditional can probably be put in yet another function to reduce the amount of code being used here
		old_x = x
		old_y = y
		x = 50
		y = 60
		dwg.add(dwg.rect((x-65, y-2), (45, 14), fill="yellow"))
		dwg.add(dwg.text(uniprot, insert = (x-45,y+7), text_anchor='middle', dominant_baseline='central', font_size='10px', font_family='Arial', font_weight='bold', fill='black'))
	else:
		dwg.add(dwg.text(uniprot, insert = (x-45,y+7), text_anchor='middle', dominant_baseline='central', font_size='10px', font_family='Arial', font_weight='bold', fill='black'))
	#charactercount = 0
	totalcount = 0
	if startingpoint <= 0:
		startnumberlabel = 1
	elif startingpoint >= maxcharactercnt:
		startnumberlabel = maxcharactercnt
	else:
		startnumberlabel = startingpoint 
	charactercount = 0
	tempfeat = {}
	featcount = 0
	for i, letter in enumerate(seq, start=1):
	    totalcount += 1		#### gives the alignment position, including gaps
	    letter = seq[i-1]
	    if letter != "-":
	    	charactercount += 1
	    	if totalcount <= distance_end:	### distance_end refers to the last alignment position that will be considered, which is +20 non-gap residues from the input position
			testlenge = int(distance_end)-int(totalcount)				
			if testlenge <= maximumdistance:	### checks that we still operate around the position of interest +/- residues only
			    if totalcount >= distance_start:
				if totalcount not in forbidden:
					if namus == poi:
					    viewboxcounter += 1
					    if startnumberlabel == startposition:
							dwg.add(dwg.rect((x, 40), (10, 14*float(Konserve[startnumberlabel][0])), fill="black"))
        			        		dwg.add(dwg.text(str(startnumberlabel), insert=(x+5, 37), text_anchor='middle', dominant_baseline='central', font_size='8px', font_family='Arial', font_weight='bold', fill='red'))			
					    else:
						if int(startnumberlabel)>= startingpoint:
							dwg.add(dwg.rect((x, 40), (10, 14*float(Konserve[startnumberlabel][0])), fill="black"))
							if int(startnumberlabel)%10 == False:
								dwg.add(dwg.text(str(startnumberlabel), insert=(x+5, 37), text_anchor='middle', dominant_baseline='central', font_size='8px', font_family='Arial', font_weight='bold', fill='black'))
					    for feat in proteinfeatures:
						if startnumberlabel in proteinfeatures[feat]:
							if tempfeat.has_key(feat)==False:
								tempfeat[feat]=[featurecolors[featcount],featcount]
								featcount+=1
							elevator = tempfeat[feat][1]
							elevator_floor = 0
							if elevator >= 3:
								if elevator_floor <= 3:
									elevator = elevator_floor
									elevator_floor += 1
								else:
									elevator_floor = 0
									elevator = elevator_floor
							y_level = 22 + (elevator*3)
							dwg.add(dwg.rect((x, y_level), (10, 2), fill=tempfeat[feat][0]))
							if "done" not in tempfeat[feat]:
								dwg.add(dwg.text(str(feat), insert=(x+15, 20), text_anchor='middle', dominant_baseline='central', font_size='8px', font_family='Arial', font_weight='bold', fill=tempfeat[feat][0]))
								tempfeat[feat].append("done")			
							


					    startnumberlabel+=1

#					if letter == "Y":
#      				        	dwg.add(dwg.rect((x, y-2), (10, 14), fill=colors['Y']))
#      				        	dwg.add(dwg.text(letter, insert=(x+5, y+8), text_anchor='middle', dominant_baseline='central', font_size='10px', font_family='Arial', font_weight='bold', fill='white'))
					try:
			        		    if charactercount in positions[namus]["VARIANT"]:
	        				        dwg.add(dwg.rect((x, y-2), (10, 14), fill=colordict['VARIANT']))
	        				        dwg.add(dwg.text(letter, insert=(x+5, y+8), text_anchor='middle', dominant_baseline='central', font_size='10px', font_family='Arial', font_weight='bold', fill='black'))
	        				    elif charactercount in positions[namus]["MUTAGEN"]:
	        				        dwg.add(dwg.rect((x, y-2), (10, 14), fill=colordict['MUTAGEN']))
	        				        dwg.add(dwg.text(letter, insert=(x+5, y+8), text_anchor='middle', dominant_baseline='central', font_size='10px', font_family='Arial', font_weight='bold', fill='black'))	
        					    elif charactercount in positions[namus]["BINDING"]:
        					        dwg.add(dwg.rect((x, y-2), (10, 14), fill=colordict['BINDING']))
        					        dwg.add(dwg.text(letter, insert=(x+5, y+8), text_anchor='middle', dominant_baseline='central', font_size='10px', font_family='Arial', font_weight='bold', 	fill='black'))
        					    elif charactercount in positions[namus]["MOD_RES"]:
        					        dwg.add(dwg.rect((x, y-2), (10, 14), fill=colordict['MOD_RES']))
        					        dwg.add(dwg.text(letter, insert=(x+5, y+8), text_anchor='middle', dominant_baseline='central', font_size='10px', font_family='Arial', font_weight='bold', fill='white'))
        					    elif charactercount in positions[namus]["ACT_SITE"]:
        					        dwg.add(dwg.rect((x, y-2), (10, 14), fill=colordict['ACT_SITE']))
        					        dwg.add(dwg.text(letter, insert=(x+5, y+8), text_anchor='middle', dominant_baseline='central', font_size='10px', font_family='Arial', font_weight='bold', fill='black'))
        					    else:
        					        dwg.add(dwg.text(letter, insert=(x+5, y+8), text_anchor='middle', dominant_baseline='central', font_size='10px', font_family='Arial', font_weight='bold', fill='black'))
				    	except:
						dwg.add(dwg.text(letter, insert=(x+5, y+8), text_anchor='middle', dominant_baseline='central', font_size='10px', font_family='Arial', font_weight='bold', fill='black'))	
        			    	x += 10
				    
	    else:	### will draw just a "-" for a gap in the alignment
		if totalcount >= distance_start:
			if totalcount <= distance_end:
				if totalcount not in forbidden:
					dwg.add(dwg.text(letter, insert=(x+5, y+8), text_anchor='middle', dominant_baseline='central', font_size='10px', font_family='Arial', font_weight='bold', fill='white'))	
					x += 10
	if namus == poi:
		dwg.add(dwg.rect((-15,y-2),(x+15,14), fill="none",stroke="black",stroke_width=1))	
		x = 50
		y = old_y
	else:
	        x = 50
 	        y += 20


    viewboxwidth = (viewboxcounter+10)*10
    viewboxheight = len(sequences_dict)*20+100
    dwg.viewbox(-15, 0,viewboxwidth,viewboxheight)
    

    x = 50
    y = 0
    for category in colors:
	 dwg.add(dwg.rect((x-30, y), (60, 10), fill=colors[category]))
    	 dwg.add(dwg.text(category, insert=(x, y+5), text_anchor='middle', dominant_baseline='central', font_size='10px', font_family='Arial', font_weight='bold', fill='black'))
 	 x += 60	
    dwg.save()






# ---------------------------------------------------------------------------------------------------------------------------------------------


alignmentfile = "/home/bq_tschmenger/Downloads/clustalo-I20230119-084041-0905-58774427-p1m.clustal_num"		#### change this to the location of the alignmentfile.
###
sequences 	= CUSTOM_ALIGN(alignmentfile)
Konserve, TheForbiddenPositions 	= conservation_checker("P61586",sequences)

### note: This is the real CONNECTORalpha dictionary I could fetch from uniprot on 31.01.2023
positions =  {'A4D1S5': {'BINDING': [24,
                        25,
                        26,
                        27,
                        28,
                        29,
                        30,
                        31,
                        72,
                        73,
                        74,
                        75,
                        76,
                        130,
                        131,
                        132,
                        133]},
 'A6NIZ1': {'BINDING': [10,
                        11,
                        12,
                        13,
                        14,
                        15,
                        16,
                        17,
                        57,
                        58,
                        59,
                        60,
                        61,
                        116,
                        117,
                        118,
                        119],
            'MOD_RES': [39, 179]},
 'O00194': {'BINDING': [16,
                        17,
                        18,
                        19,
                        20,
                        21,
                        22,
                        23,
                        24,
                        74,
                        75,
                        76,
                        77,
                        78,
                        133,
                        134,
                        135,
                        136,
                        163,
                        164,
                        165],
            'MUTAGEN': [78],
            'VARIANT': [92]},
 'O00212': {'BINDING': [24,
                        25,
                        26,
                        27,
                        28,
                        29,
                        30,
                        31,
                        71,
                        72,
                        73,
                        74,
                        75,
                        129,
                        130,
                        131,
                        132],
            'VARIANT': [134]},
 'O14807': {'BINDING': [20,
                        21,
                        22,
                        23,
                        24,
                        25,
                        26,
                        27,
                        67,
                        68,
                        69,
                        70,
                        71,
                        126,
                        127,
                        128,
                        129],
            'VARIANT': [23, 68, 71]},
 'O14966': {'BINDING': [14,
                        15,
                        16,
                        17,
                        18,
                        19,
                        20,
                        21,
                        33,
                        34,
                        35,
                        36,
                        37,
                        38,
                        39,
                        63,
                        64,
                        65,
                        66,
                        67,
                        125,
                        126,
                        127,
                        128,
                        156,
                        157],
            'MOD_RES': [71, 72],
            'MUTAGEN': [71, 71, 72, 72, 73, 75]},
 'O94844': {'BINDING': [21,
                        22,
                        23,
                        24,
                        25,
                        26,
                        27,
                        28,
                        84,
                        85,
                        86,
                        87,
                        88,
                        140,
                        141,
                        142,
                        143]},
 'O95057': {'BINDING': [17,
                        18,
                        19,
                        20,
                        21,
                        22,
                        33,
                        34,
                        35,
                        36,
                        37,
                        38,
                        39,
                        61,
                        62,
                        63,
                        64,
                        65,
                        121,
                        122,
                        123,
                        124,
                        125,
                        151,
                        151,
                        152]},
 'O95716': {'BINDING': [29,
                        30,
                        31,
                        32,
                        33,
                        34,
                        35,
                        36,
                        37,
                        48,
                        49,
                        50,
                        51,
                        52,
                        53,
                        54,
                        77,
                        78,
                        79,
                        80,
                        81,
                        135,
                        136,
                        137,
                        138,
                        165,
                        166,
                        167],
            'MOD_RES': [86, 190],
            'MUTAGEN': [86],
            'VARIANT': [64]},
 'O95755': {'BINDING': [130,
                        131,
                        132,
                        133,
                        134,
                        135,
                        136,
                        137,
                        178,
                        179,
                        180,
                        181,
                        182,
                        237,
                        238,
                        239,
                        240]},
 'P01111': {'BINDING': [10,
                        11,
                        12,
                        13,
                        14,
                        15,
                        16,
                        17,
                        18,
                        29,
                        30,
                        57,
                        58,
                        59,
                        60,
                        61,
                        116,
                        117,
                        118,
                        119],
            'MOD_RES': [89],
            'MUTAGEN': [89, 164],
            'VARIANT': [12, 12, 13, 13, 34, 50, 60, 61, 61]},
 'P01112': {'BINDING': [13,
                        14,
                        15,
                        16,
                        17,
                        18,
                        29,
                        30,
                        31,
                        32,
                        33,
                        34,
                        35,
                        59,
                        60,
                        116,
                        117,
                        118,
                        119,
                        145,
                        146,
                        147],
            'MOD_RES': [1, 2, 118],
            'MUTAGEN': [17,
                        26,
                        29,
                        32,
                        34,
                        35,
                        38,
                        39,
                        59,
                        61,
                        83,
                        118,
                        119,
                        144,
                        164,
                        167,
                        170,
                        184],
            'VARIANT': [12,
                        12,
                        12,
                        12,
                        12,
                        12,
                        13,
                        13,
                        13,
                        22,
                        58,
                        61,
                        61,
                        63,
                        89,
                        117,
                        146,
                        146]},
 'P01116': {'BINDING': [10,
                        11,
                        12,
                        13,
                        14,
                        15,
                        16,
                        17,
                        18,
                        29,
                        30,
                        31,
                        32,
                        33,
                        34,
                        35,
                        59,
                        60,
                        116,
                        117,
                        118,
                        119],
            'MOD_RES': [1, 2, 104],
            'MUTAGEN': [1116, 182],
            'VARIANT': [5,
                        5,
                        10,
                        12,
                        12,
                        12,
                        1116,
                        12,
                        12,
                        12,
                        1116,
                        13,
                        13,
                        14,
                        19,
                        22,
                        22,
                        36,
                        59,
                        60,
                        1116,
                        60,
                        61,
                        61,
                        71,
                        117,
                        1116,
                        146,
                        146,
                        147]},
 'P08134': {'BINDING': [12,
                        13,
                        14,
                        15,
                        16,
                        17,
                        18,
                        19,
                        59,
                        60,
                        61,
                        62,
                        63,
                        117,
                        118,
                        119,
                        120],
            'MOD_RES': [41, 190],
            'VARIANT': [120]},
 'P10114': {'BINDING': [10,
                        11,
                        12,
                        13,
                        14,
                        15,
                        16,
                        17,
                        57,
                        58,
                        59,
                        60,
                        61,
                        116,
                        117,
                        118,
                        119],
            'MUTAGEN': [5, 12, 17, 35, 39, 94, 145, 148, 150]},
 'P10301': {'BINDING': [36,
                        37,
                        38,
                        39,
                        40,
                        41,
                        42,
                        43,
                        44,
                        83,
                        84,
                        85,
                        86,
                        87,
                        142,
                        143,
                        144,
                        145,
                        172,
                        173,
                        174],
            'MUTAGEN': [38, 43]},
 'P11233': {'BINDING': [24,
                        25,
                        26,
                        27,
                        28,
                        29,
                        40,
                        41,
                        42,
                        43,
                        44,
                        45,
                        46,
                        127,
                        128,
                        129,
                        130],
            'MUTAGEN': [23, 38, 46, 47, 47, 49, 49, 50, 52, 52, 72, 81, 81],
            'VARIANT': [25, 25, 128, 130, 157, 158, 176]},
 'P11234': {'BINDING': [21,
                        22,
                        23,
                        24,
                        25,
                        26,
                        27,
                        28,
                        29,
                        68,
                        69,
                        70,
                        71,
                        72,
                        128,
                        129,
                        130,
                        131,
                        158,
                        159,
                        160],
            'MUTAGEN': [23, 38, 46, 46, 49, 49, 72]},
 'P15153': {'BINDING': [10,
                        11,
                        12,
                        13,
                        14,
                        15,
                        16,
                        17,
                        57,
                        58,
                        59,
                        60,
                        61,
                        115,
                        116,
                        117,
                        118],
            'MOD_RES': [39, 147, 189],
            'MUTAGEN': [189],
            'VARIANT': [29, 34, 56, 57, 62, 92]},
 'P17081': {'BINDING': [16,
                        17,
                        18,
                        19,
                        20,
                        21,
                        22,
                        23,
                        63,
                        64,
                        65,
                        66,
                        67,
                        121,
                        122,
                        123,
                        124],
            'MUTAGEN': [23, 44, 67]},
 'P20336': {'BINDING': [29,
                        30,
                        31,
                        32,
                        33,
                        34,
                        35,
                        36,
                        37,
                        48,
                        49,
                        50,
                        51,
                        52,
                        53,
                        54,
                        77,
                        78,
                        79,
                        80,
                        81,
                        135,
                        136,
                        137,
                        138,
                        165,
                        166,
                        167],
            'MOD_RES': [86, 188, 190],
            'MUTAGEN': [86, 86]},
 'P20337': {'BINDING': [29,
                        30,
                        31,
                        32,
                        33,
                        34,
                        35,
                        36,
                        37,
                        48,
                        49,
                        50,
                        51,
                        52,
                        53,
                        54,
                        77,
                        78,
                        79,
                        80,
                        81,
                        135,
                        136,
                        137,
                        138,
                        165,
                        166,
                        167],
            'MOD_RES': [86, 188, 190],
            'MUTAGEN': [86, 86]},
 'P20338': {'BINDING': [20,
                        21,
                        22,
                        23,
                        24,
                        25,
                        26,
                        27,
                        28,
                        68,
                        69,
                        70,
                        71,
                        72,
                        126,
                        127,
                        128,
                        129,
                        156,
                        157,
                        158],
            'MOD_RES': [72, 218],
            'MUTAGEN': [51, 51]},
 'P20339': {'BINDING': [27,
                        28,
                        29,
                        30,
                        31,
                        32,
                        33,
                        34,
                        35,
                        46,
                        47,
                        48,
                        49,
                        50,
                        51,
                        52,
                        75,
                        76,
                        77,
                        78,
                        79,
                        133,
                        134,
                        135,
                        136,
                        163,
                        164,
                        165],
            'MOD_RES': [84],
            'MUTAGEN': [54, 56, 57, 74, 79, 82, 84, 84, 89, 116, 120]},
 'P20340': {'BINDING': [20,
                        21,
                        22,
                        23,
                        24,
                        25,
                        26,
                        27,
                        28,
                        68,
                        69,
                        70,
                        71,
                        72,
                        126,
                        127,
                        128,
                        129,
                        156,
                        157,
                        158],
            'MOD_RES': [82, 184, 208],
            'MUTAGEN': [27, 46, 72]},
 'P51148': {'BINDING': [28,
                        29,
                        30,
                        31,
                        32,
                        33,
                        34,
                        35,
                        36,
                        47,
                        48,
                        49,
                        50,
                        51,
                        52,
                        53,
                        76,
                        77,
                        78,
                        79,
                        80,
                        134,
                        135,
                        136,
                        137,
                        164,
                        165,
                        166],
            'MOD_RES': [85],
            'MUTAGEN': [85, 85],
            'VARIANT': [40]},
 'P51149': {'BINDING': [15,
                        16,
                        17,
                        18,
                        19,
                        20,
                        21,
                        22,
                        34,
                        35,
                        36,
                        37,
                        38,
                        39,
                        40,
                        63,
                        64,
                        65,
                        66,
                        67,
                        125,
                        126,
                        127,
                        128,
                        156,
                        157],
            'MOD_RES': [72],
            'MUTAGEN': [8, 10, 22, 67, 180, 183],
            'VARIANT': [32, 157, 161, 162]},
 'P51151': {'BINDING': [14,
                        15,
                        16,
                        17,
                        18,
                        19,
                        20,
                        21,
                        22,
                        62,
                        63,
                        64,
                        65,
                        66,
                        124,
                        125,
                        126,
                        127,
                        155],
            'MOD_RES': [179],
            'MUTAGEN': [40, 44, 61, 66]},
 'P51153': {'BINDING': [15,
                        16,
                        17,
                        18,
                        19,
                        20,
                        21,
                        22,
                        23,
                        63,
                        64,
                        65,
                        66,
                        67,
                        121,
                        122,
                        123,
                        124],
            'MOD_RES': [200],
            'MUTAGEN': [22, 67]},
 'P51157': {'BINDING': [19,
                        20,
                        21,
                        22,
                        23,
                        24,
                        25,
                        26,
                        27,
                        68,
                        69,
                        70,
                        71,
                        72,
                        129,
                        130,
                        131,
                        132,
                        159,
                        160,
                        161],
            'MOD_RES': [8]},
 'P51159': {'BINDING': [16,
                        17,
                        18,
                        19,
                        20,
                        21,
                        22,
                        23,
                        24,
                        74,
                        75,
                        76,
                        77,
                        78,
                        133,
                        134,
                        135,
                        136,
                        163,
                        164,
                        165],
            'MUTAGEN': [23, 70, 76, 78],
            'VARIANT': [84, 152]},
 'P52198': {'BINDING': [14,
                        15,
                        16,
                        17,
                        18,
                        19,
                        20,
                        21,
                        61,
                        62,
                        63,
                        64,
                        65,
                        119,
                        120,
                        121,
                        122]},
 'P59190': {'BINDING': [15,
                        16,
                        17,
                        18,
                        19,
                        20,
                        21,
                        22,
                        63,
                        64,
                        65,
                        66,
                        67,
                        121,
                        122,
                        123,
                        124]},
 'P60763': {'BINDING': [10,
                        11,
                        12,
                        13,
                        14,
                        15,
                        16,
                        17,
                        57,
                        58,
                        59,
                        60,
                        61,
                        115,
                        116,
                        117,
                        118],
            'MOD_RES': [189],
            'VARIANT': [29, 59, 61, 62]},
 'P60953': {'BINDING': [10,
                        11,
                        12,
                        13,
                        14,
                        15,
                        16,
                        17,
                        57,
                        58,
                        59,
                        60,
                        61,
                        115,
                        116,
                        117,
                        118],
            'MOD_RES': [32, 35, 64, 188],
            'MUTAGEN': [12, 17, 32, 61],
            'VARIANT': [64]},
 'P61006': {'BINDING': [17,
                        18,
                        19,
                        20,
                        21,
                        22,
                        34,
                        35,
                        36,
                        37,
                        38,
                        39,
                        40,
                        63,
                        64,
                        65,
                        66,
                        67,
                        121,
                        122,
                        123,
                        124,
                        152,
                        153,
                        154],
            'MOD_RES': [72, 204],
            'MUTAGEN': [22, 67, 72, 72]},
 'P61018': {'BINDING': [15,
                        16,
                        17,
                        18,
                        19,
                        20,
                        21,
                        22,
                        23,
                        63,
                        64,
                        65,
                        66,
                        67,
                        121,
                        122,
                        123,
                        124,
                        151,
                        152,
                        153],
            'MOD_RES': [67, 213]},
 'P61019': {'BINDING': [13,
                        14,
                        15,
                        16,
                        17,
                        18,
                        19,
                        20,
                        21,
                        61,
                        62,
                        63,
                        64,
                        65,
                        119,
                        120,
                        121,
                        122,
                        149,
                        150,
                        151],
            'MOD_RES': [2]},
 'P61020': {'BINDING': [27,
                        28,
                        29,
                        30,
                        31,
                        32,
                        33,
                        34,
                        35,
                        46,
                        47,
                        48,
                        49,
                        50,
                        51,
                        52,
                        75,
                        76,
                        77,
                        78,
                        79,
                        133,
                        134,
                        135,
                        136,
                        163,
                        164,
                        165],
            'MOD_RES': [84],
            'MUTAGEN': [34, 79, 84, 84]},
 'P61026': {'BINDING': [18,
                        19,
                        20,
                        21,
                        22,
                        23,
                        24,
                        35,
                        36,
                        37,
                        38,
                        39,
                        40,
                        41,
                        64,
                        65,
                        66,
                        67,
                        68,
                        122,
                        123,
                        124,
                        125,
                        152,
                        153,
                        154],
            'MOD_RES': [73, 102],
            'MUTAGEN': [23, 68, 73, 73]},
 'P61106': {'BINDING': [18,
                        19,
                        20,
                        21,
                        22,
                        23,
                        24,
                        25,
                        26,
                        66,
                        67,
                        68,
                        69,
                        70,
                        124,
                        125,
                        126,
                        127,
                        154,
                        155,
                        156],
            'MOD_RES': [215]},
 'P61224': {'BINDING': [10,
                        11,
                        12,
                        13,
                        14,
                        15,
                        16,
                        17,
                        18,
                        57,
                        58,
                        59,
                        60,
                        61,
                        116,
                        117,
                        118,
                        119,
                        147,
                        148,
                        149],
            'MOD_RES': [39, 179],
            'MUTAGEN': [12, 32, 38, 64, 179]},
 'P61225': {'BINDING': [10,
                        11,
                        12,
                        13,
                        14,
                        15,
                        16,
                        17,
                        57,
                        58,
                        59,
                        60,
                        61,
                        116,
                        117,
                        118,
                        119]},
 'P61586': {'BINDING': [12,
                        13,
                        14,
                        15,
                        16,
                        17,
                        18,
                        19,
                        30,
                        31,
                        32,
                        33,
                        34,
                        35,
                        36,
                        37,
                        59,
                        60,
                        61,
                        62,
                        63,
                        160,
                        161,
                        162,
                        117,
                        118,
                        119,
                        120],
            'MOD_RES': [41, 188, 190, 37, 34, 63],
            'MUTAGEN': [37, 34, 34, 14, 19, 193, 63],
            'VARIANT': [47, 71]},
 'P61587': {'BINDING': [30,
                        31,
                        32,
                        33,
                        34,
                        35,
                        36,
                        37,
                        77,
                        78,
                        79,
                        80,
                        81,
                        135,
                        136,
                        137,
                        138]},
 'P62491': {'BINDING': [18,
                        19,
                        20,
                        21,
                        22,
                        23,
                        24,
                        25,
                        26,
                        37,
                        38,
                        39,
                        40,
                        41,
                        42,
                        43,
                        66,
                        67,
                        68,
                        69,
                        70,
                        124,
                        125,
                        126,
                        127,
                        154,
                        155,
                        156],
            'MUTAGEN': [13, 22, 24, 25, 36, 38, 40, 41, 41, 44, 70, 82, 154]},
 'P62745': {'BINDING': [12,
                        13,
                        14,
                        15,
                        16,
                        17,
                        18,
                        19,
                        59,
                        60,
                        61,
                        62,
                        63,
                        117,
                        118,
                        119,
                        120],
            'MOD_RES': [41, 154],
            'MUTAGEN': [14, 39, 189, 192]},
 'P62820': {'BINDING': [18,
                        19,
                        20,
                        21,
                        22,
                        23,
                        24,
                        25,
                        26,
                        36,
                        37,
                        38,
                        39,
                        40,
                        41,
                        42,
                        43,
                        66,
                        67,
                        68,
                        69,
                        70,
                        124,
                        125,
                        126,
                        127,
                        154,
                        155,
                        156],
            'MOD_RES': [79],
            'MUTAGEN': [72, 74, 82, 111, 124]},
 'P62826': {'BINDING': [18,
                        19,
                        20,
                        21,
                        22,
                        23,
                        24,
                        25,
                        36,
                        37,
                        38,
                        39,
                        40,
                        41,
                        42,
                        68,
                        122,
                        123,
                        124,
                        125,
                        150,
                        151,
                        152],
            'MOD_RES': [24, 37, 60, 71, 99, 134, 159],
            'MUTAGEN': [19, 24, 24, 25, 37, 37, 39, 69, 69, 70, 76, 134, 134]},
 'P62834': {'BINDING': [10,
                        11,
                        12,
                        13,
                        14,
                        15,
                        16,
                        17,
                        18,
                        29,
                        30,
                        31,
                        32,
                        33,
                        34,
                        35,
                        60,
                        116,
                        117,
                        118,
                        119]},
 'P63000': {'BINDING': [13,
                        14,
                        15,
                        16,
                        17,
                        18,
                        30,
                        31,
                        32,
                        33,
                        34,
                        35,
                        60,
                        116,
                        117,
                        118,
                        159,
                        160],
            'MOD_RES': [32, 35, 63000, 189],
            'MUTAGEN': [17,
                        30,
                        32,
                        35,
                        35,
                        37,
                        56,
                        61,
                        67,
                        70,
                        183,
                        183,
                        184,
                        185,
                        186,
                        188],
            'VARIANT': [18, 26, 51, 51, 59, 73, 93, 157, 180]},
 'P84095': {'BINDING': [10,
                        11,
                        12,
                        13,
                        14,
                        15,
                        16,
                        17,
                        57,
                        58,
                        59,
                        60,
                        61,
                        115,
                        116,
                        117,
                        118],
            'MOD_RES': [39, 138, 180, 188]},
 'Q12829': {'BINDING': [21,
                        22,
                        23,
                        24,
                        25,
                        26,
                        27,
                        28,
                        69,
                        70,
                        71,
                        72,
                        73,
                        126,
                        127,
                        128,
                        129]},
 'Q14088': {'BINDING': [43,
                        44,
                        45,
                        46,
                        47,
                        48,
                        49,
                        50,
                        91,
                        92,
                        93,
                        94,
                        95,
                        151,
                        152,
                        153,
                        154]},
 'Q14964': {'BINDING': [15,
                        16,
                        17,
                        18,
                        19,
                        20,
                        21,
                        22,
                        68,
                        69,
                        70,
                        71,
                        72,
                        127,
                        128,
                        129,
                        130],
            'MUTAGEN': [34]},
 'Q15286': {'BINDING': [15,
                        16,
                        17,
                        18,
                        19,
                        20,
                        21,
                        22,
                        23,
                        33,
                        34,
                        35,
                        36,
                        37,
                        38,
                        39,
                        40,
                        63,
                        64,
                        65,
                        66,
                        67,
                        120,
                        121,
                        122,
                        123,
                        150,
                        151,
                        152],
            'MOD_RES': [72, 75, 77],
            'MUTAGEN': [22, 67, 72, 72]},
 'Q15382': {'BINDING': [16,
                        17,
                        18,
                        19,
                        20,
                        20,
                        21,
                        32,
                        33,
                        34,
                        35,
                        36,
                        37,
                        38,
                        38,
                        63,
                        119,
                        120,
                        121,
                        122,
                        149,
                        150],
            'MOD_RES': [130],
            'MUTAGEN': [15,
                        20,
                        38,
                        39,
                        41,
                        43,
                        46,
                        48,
                        49,
                        53,
                        54,
                        56,
                        60,
                        64],
            'VARIANT': [139]},
 'Q15669': {'BINDING': [11,
                        12,
                        13,
                        14,
                        15,
                        16,
                        17,
                        18,
                        58,
                        59,
                        60,
                        61,
                        62,
                        116,
                        117,
                        118,
                        119],
            'VARIANT': [38]},
 'Q15771': {'BINDING': [16,
                        17,
                        18,
                        19,
                        20,
                        21,
                        22,
                        23,
                        64,
                        65,
                        66,
                        67,
                        68,
                        122,
                        123,
                        124,
                        125]},
 'Q15907': {'BINDING': [18,
                        19,
                        20,
                        21,
                        22,
                        23,
                        24,
                        25,
                        26,
                        66,
                        67,
                        68,
                        69,
                        70,
                        124,
                        125,
                        126,
                        127,
                        154,
                        155,
                        156],
            'MUTAGEN': [25, 70],
            'VARIANT': [22, 68]},
 'Q53S08': {'BINDING': [20,
                        21,
                        22,
                        23,
                        24,
                        25,
                        26,
                        27,
                        28,
                        38,
                        39,
                        40,
                        41,
                        42,
                        43,
                        44,
                        45,
                        68,
                        69,
                        70,
                        71,
                        72,
                        126,
                        127,
                        128,
                        129,
                        156,
                        157,
                        158]},
 'Q5JT25': {'BINDING': [38,
                        39,
                        40,
                        41,
                        42,
                        43,
                        44,
                        45,
                        86,
                        87,
                        88,
                        89,
                        90,
                        144,
                        145,
                        146,
                        147]},
 'Q6IQ22': {'BINDING': [49,
                        50,
                        51,
                        52,
                        53,
                        54,
                        55,
                        56,
                        57,
                        97,
                        98,
                        99,
                        100,
                        101,
                        155,
                        156,
                        157,
                        158,
                        159,
                        187,
                        188],
            'MOD_RES': [106],
            'MUTAGEN': [106, 106]},
 'Q7L0Q8': {'BINDING': [56,
                        57,
                        58,
                        59,
                        60,
                        61,
                        62,
                        63,
                        103,
                        104,
                        105,
                        106,
                        107,
                        161,
                        162,
                        163,
                        164],
            'MUTAGEN': [80, 81, 83, 83, 86, 107, 255],
            'VARIANT': [121]},
 'Q7Z444': {'BINDING': [48,
                        49,
                        50,
                        51,
                        52,
                        53,
                        54,
                        55,
                        95,
                        96,
                        97,
                        98,
                        99,
                        151,
                        152,
                        153,
                        154]},
 'Q86YS6': {'BINDING': [25,
                        26,
                        27,
                        28,
                        29,
                        30,
                        31,
                        32,
                        73,
                        74,
                        75,
                        76,
                        77,
                        131,
                        132,
                        133,
                        134,
                        163,
                        164],
            'MOD_RES': [49, 82],
            'MUTAGEN': [32, 82, 82]},
 'Q8IXI1': {'BINDING': [11,
                        12,
                        13,
                        14,
                        15,
                        16,
                        17,
                        18,
                        57,
                        58,
                        59,
                        60,
                        61,
                        118,
                        119,
                        120,
                        121],
            'MUTAGEN': [13, 18]},
 'Q8IYK8': {'BINDING': [121,
                        122,
                        123,
                        124,
                        125,
                        126,
                        127,
                        128,
                        229,
                        230,
                        231,
                        232,
                        260,
                        261]},
 'Q8IZ41': {'BINDING': [551,
                        552,
                        553,
                        554,
                        555,
                        556,
                        654,
                        655,
                        656,
                        657,
                        691,
                        692],
            'MUTAGEN': [555, 600]},
 'Q8TAI7': {'BINDING': [16,
                        17,
                        18,
                        19,
                        20,
                        21,
                        32,
                        33,
                        34,
                        35,
                        36,
                        37,
                        38,
                        38,
                        63,
                        119,
                        120,
                        121,
                        122,
                        149,
                        150],
            'MUTAGEN': [41, 54, 56, 60, 64]},
 'Q8WUD1': {'BINDING': [13,
                        14,
                        15,
                        16,
                        17,
                        18,
                        19,
                        20,
                        21,
                        61,
                        62,
                        63,
                        64,
                        65,
                        119,
                        120,
                        121,
                        122,
                        149,
                        150,
                        151],
            'VARIANT': [212]},
 'Q92730': {'BINDING': [23,
                        24,
                        25,
                        26,
                        27,
                        28,
                        38,
                        39,
                        40,
                        41,
                        42,
                        43,
                        44,
                        45,
                        67,
                        68,
                        69,
                        70,
                        71,
                        125,
                        126,
                        127,
                        128,
                        169,
                        170],
            'MUTAGEN': [45],
            'VARIANT': [44]},
 'Q92928': {'BINDING': [15,
                        16,
                        17,
                        18,
                        19,
                        20,
                        21,
                        22,
                        23,
                        33,
                        34,
                        35,
                        36,
                        37,
                        38,
                        39,
                        40,
                        63,
                        64,
                        65,
                        66,
                        67,
                        121,
                        122,
                        123,
                        124,
                        151,
                        152,
                        153],
            'MOD_RES': [76]},
 'Q92930': {'BINDING': [15,
                        16,
                        17,
                        18,
                        19,
                        20,
                        21,
                        22,
                        63,
                        64,
                        65,
                        66,
                        67,
                        121,
                        122,
                        123,
                        124],
            'MOD_RES': [72, 180, 204],
            'MUTAGEN': [72, 72]},
 'Q92963': {'BINDING': [28,
                        29,
                        30,
                        31,
                        32,
                        33,
                        34,
                        35,
                        75,
                        76,
                        77,
                        78,
                        79,
                        134,
                        135,
                        136,
                        137],
            'MUTAGEN': [35, 53, 79],
            'VARIANT': [35, 57, 81, 82, 82, 83, 90, 95]},
 'Q96AX2': {'BINDING': [36,
                        37,
                        38,
                        39,
                        40,
                        41,
                        42,
                        43,
                        85,
                        86,
                        87,
                        88,
                        89,
                        143,
                        144,
                        145,
                        146]},
 'Q96DA2': {'BINDING': [15,
                        16,
                        17,
                        18,
                        19,
                        20,
                        21,
                        22,
                        64,
                        65,
                        66,
                        67,
                        68,
                        123,
                        124,
                        125,
                        126],
            'MUTAGEN': [22, 68],
            'VARIANT': [168]},
 'Q96E17': {'BINDING': [37,
                        38,
                        39,
                        40,
                        41,
                        42,
                        43,
                        44,
                        45,
                        56,
                        57,
                        58,
                        59,
                        60,
                        61,
                        62,
                        85,
                        86,
                        87,
                        88,
                        89,
                        143,
                        144,
                        145,
                        146,
                        173,
                        174,
                        175],
            'MOD_RES': [94, 196, 198],
            'MUTAGEN': [94, 94]},
 'Q96HU8': {'BINDING': [14,
                        15,
                        16,
                        17,
                        18,
                        19,
                        20,
                        21,
                        33,
                        34,
                        35,
                        36,
                        37,
                        38,
                        39,
                        61,
                        62,
                        63,
                        64,
                        65,
                        121,
                        122,
                        123,
                        124,
                        152,
                        153],
            'MOD_RES': [35, 126]},
 'Q96L33': {'BINDING': [38,
                        39,
                        40,
                        41,
                        42,
                        43,
                        44,
                        45,
                        85,
                        86,
                        87,
                        88,
                        89,
                        143,
                        144,
                        145,
                        146]},
 'Q99578': {'BINDING': [27,
                        28,
                        29,
                        30,
                        31,
                        32,
                        33,
                        34,
                        74,
                        75,
                        76,
                        77,
                        78,
                        133,
                        134,
                        135,
                        136]},
 'Q9BSW2': {'BINDING': [552,
                        553,
                        554,
                        555,
                        556,
                        557,
                        558,
                        559,
                        600,
                        601,
                        602,
                        603,
                        604,
                        659,
                        660,
                        661],
            'MUTAGEN': [559, 604, 658]},
 'Q9BYZ6': {'BINDING': [21,
                        22,
                        23,
                        24,
                        25,
                        26,
                        27,
                        28,
                        84,
                        85,
                        86,
                        87,
                        88,
                        140,
                        141,
                        142,
                        143]},
 'Q9BZG1': {'BINDING': [59,
                        60,
                        61,
                        62,
                        63,
                        64,
                        65,
                        66,
                        107,
                        108,
                        109,
                        110,
                        111,
                        166,
                        167,
                        168,
                        169],
            'VARIANT': [197]},
 'Q9H082': {'BINDING': [39,
                        40,
                        41,
                        42,
                        43,
                        44,
                        45,
                        46,
                        88,
                        89,
                        90,
                        91,
                        92,
                        148,
                        149,
                        150,
                        151],
            'MUTAGEN': [92],
            'VARIANT': [46, 148]},
 'Q9H0N0': {'BINDING': [20,
                        21,
                        22,
                        23,
                        24,
                        25,
                        26,
                        27,
                        68,
                        69,
                        70,
                        71,
                        72,
                        126,
                        127,
                        128,
                        129],
            'MOD_RES': [82],
            'MUTAGEN': [25, 45],
            'VARIANT': [159]},
 'Q9H0T7': {'BINDING': [26,
                        27,
                        28,
                        29,
                        30,
                        31,
                        32,
                        33,
                        73,
                        74,
                        75,
                        76,
                        77,
                        132,
                        133,
                        134,
                        135],
            'MOD_RES': [29],
            'VARIANT': [19, 184]},
 'Q9H0U4': {'BINDING': [15,
                        16,
                        17,
                        18,
                        19,
                        20,
                        21,
                        22,
                        23,
                        33,
                        34,
                        35,
                        36,
                        37,
                        38,
                        39,
                        40,
                        63,
                        64,
                        65,
                        66,
                        67,
                        121,
                        122,
                        123,
                        124,
                        151,
                        152,
                        153],
            'MOD_RES': [76, 77],
            'MUTAGEN': [67, 73, 76, 77, 78, 81, 103, 110, 121, 137, 144]},
 'Q9H4E5': {'BINDING': [31,
                        32,
                        33,
                        34,
                        35,
                        36,
                        46,
                        47,
                        48,
                        49,
                        50,
                        51,
                        52,
                        53,
                        75,
                        76,
                        77,
                        78,
                        79,
                        133,
                        134,
                        135,
                        136,
                        177,
                        178],
            'MUTAGEN': [17, 17, 19, 30, 35, 79]},
 'Q9HBH0': {'BINDING': [26,
                        27,
                        28,
                        29,
                        30,
                        31,
                        32,
                        33,
                        73,
                        74,
                        75,
                        76,
                        77,
                        131,
                        132,
                        133,
                        134]},
 'Q9NP72': {'BINDING': [15,
                        16,
                        17,
                        18,
                        19,
                        20,
                        21,
                        22,
                        23,
                        63,
                        64,
                        65,
                        66,
                        67,
                        122,
                        123,
                        124,
                        125,
                        151,
                        152,
                        153],
            'MOD_RES': [144],
            'MUTAGEN': [67],
            'VARIANT': [24, 93, 95, 113]},
 'Q9NP90': {'BINDING': [14,
                        15,
                        16,
                        17,
                        18,
                        19,
                        20,
                        21,
                        22,
                        33,
                        34,
                        38,
                        39,
                        65,
                        124,
                        125,
                        126,
                        127,
                        155,
                        156],
            'MOD_RES': [34]},
 'Q9NRW1': {'BINDING': [20,
                        21,
                        22,
                        23,
                        24,
                        25,
                        26,
                        27,
                        45,
                        68,
                        69,
                        70,
                        71,
                        72,
                        126,
                        127,
                        128,
                        129],
            'MOD_RES': [82, 208],
            'MUTAGEN': [27, 72]},
 'Q9UBK7': {'BINDING': [28,
                        29,
                        30,
                        31,
                        32,
                        33,
                        34,
                        35,
                        76,
                        77,
                        78,
                        79,
                        80,
                        133,
                        134,
                        135,
                        136]},
 'Q9UL25': {'BINDING': [26,
                        27,
                        28,
                        29,
                        30,
                        31,
                        32,
                        33,
                        34,
                        74,
                        75,
                        76,
                        77,
                        78,
                        132,
                        133,
                        134,
                        135,
                        162,
                        163,
                        164],
            'MUTAGEN': [33, 78]},
 'Q9ULC3': {'BINDING': [16,
                        17,
                        18,
                        19,
                        20,
                        21,
                        22,
                        23,
                        64,
                        65,
                        66,
                        67,
                        68,
                        121,
                        122,
                        123,
                        124],
            'VARIANT': [12, 13, 40, 79, 85, 101]},
 'Q9ULW5': {'BINDING': [70,
                        71,
                        72,
                        73,
                        74,
                        75,
                        76,
                        77,
                        78,
                        119,
                        120,
                        121,
                        122,
                        123,
                        177,
                        178,
                        179,
                        180,
                        207,
                        208,
                        209],
            'MUTAGEN': [77, 123, 177]},
 'Q9UNT1': {'BINDING': [28,
                        29,
                        30,
                        31,
                        32,
                        33,
                        34,
                        35,
                        76,
                        77,
                        78,
                        79,
                        80,
                        133,
                        134,
                        135,
                        136],
            'MUTAGEN': [35, 73, 80]},
 'Q9Y272': {'BINDING': [31,
                        32,
                        33,
                        34,
                        35,
                        36,
                        37,
                        38,
                        78,
                        79,
                        80,
                        81,
                        82,
                        145,
                        146,
                        147,
                        148]},
 'Q9Y3L5': {'BINDING': [10,
                        11,
                        12,
                        13,
                        14,
                        15,
                        16,
                        17,
                        57,
                        58,
                        59,
                        60,
                        61,
                        116,
                        117,
                        118,
                        119]}}


### to define the annotation colors we want to use
colors = {"VARIANT":"lightgreen",
	"MUTAGEN":"salmon",
	"BINDING":"yellow",
	"MOD_RES":"purple",
	"ACT_SITE":"lightblue"}

featurecolors = ["firebrick","tomato","orange","olive","palegreen","teal","dodgerblue","blueviolet","deeppink"]
### an example feature dictionary as it could look like for kinases
feature_dict = {"Effector":[34,42],
		"Switch II":[61,78],
		"Switch I":[27,38],
		"p-loop":[13,20]}
for k in feature_dict:
	start 	= feature_dict[k][0]
	end	= feature_dict[k][1]
	for i in range(start, end+1):
		if i not in feature_dict[k]:
			feature_dict[k].append(i)

create_svg(sequences, positions, colors, 34, 20, "P61586", TheForbiddenPositions, feature_dict)	### def create_svg(sequences_dict, positions, colors, startposition, windowsize, poi):


